### ISSUE TITLE
how to properly configure this plugin

### ISSUE THREAD

**Issue by ZakharchukEduard** [mantisbt-plugins/Attachments#1]
Hi.
Could you please advise how to properly configure this plugin?
I installed it like all other plugins. I expected that after installing the plugin, the attachments section will be displayed in the task editing mode, but this section is not displayed.

**Comment by ghost** [comment]
It will be installed when viewing the issue. In Edit mode you can still add files using the notes (standard Mantis)

**Comment by ZakharchukEduard** [comment]
Thank you for your reply. But sometimes there is a need to add files exactly in the attachments section.
Can your plugin help with this?
Or do you know how to enable this section in the code?

**Comment by ghost** [comment]
Just test the latest version 2.2

**Comment by ZakharchukEduard** [comment]
I have version 2.26.0
Is it possible to finalize your plugin for this version?

**Comment by ghost** [comment]
I was not talking about Mantis version. Download the latest version of the plugin (2.2.0)  and install it. Do read the instruictions in the readme

**Comment by ZakharchukEduard** [comment]
![image](https://github.com/user-attachments/assets/957a0eab-7d0e-47b3-aa9d-506535a44a04)
I didn't understand you in the previous post. Thank you for your work.
Installed the new version of the plugin.
And when I try to open a task I get an error.
I did not understand instruictions in the readme, still need to manually make changes to certain files?

**Comment by ghost** [comment]
Yes, you do. In the readme
 it is described what needs to be done in the bug_update_page.php

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ghost** [comment]
In version 2.25, you will find a config option
